name: Test

on: [PUSH]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      -
          name: Cypress run
          uses: cypress-io/github-actions
          with:
            build: npm run build
            start: npm start